name: circular_bottom_navigation
description: Circular Bottom Navigation (or maybe a tab bar)
version: 2.1.0
homepage: https://github.com/imaNNeoFighT/circular_bottom_navigation

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter